// Code generator for precomputed Sobol direction numbers and primitive polynomials
// This tool generates a header file with static constexpr tables for improved
// runtime performance by eliminating the need to compute these at initialization.

#include <array>
#include <cstddef>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

#include "sobol/direction_numbers.hpp"
#include "sobol/primitive_polynomial.hpp"

namespace {

// Maximum number of dimensions to precompute
constexpr std::size_t kMaxPrecomputedDimensions = 1000u;

std::string format_hex(std::uint32_t value) {
  std::ostringstream oss;
  oss << "0x" << std::hex << value << "u";
  return oss.str();
}

void write_header_preamble(std::ostream& out) {
  out << R"(// GENERATED FILE - DO NOT EDIT
// This file is automatically generated by tools/generate_tables.cpp
// It contains precomputed primitive polynomials and direction numbers for Sobol sequences.
//
// Generation ensures Property A is enforced (Joe-Kuo method) through full-rank checks
// of initial direction numbers for each dimension.

#ifndef SOBOL_PRECOMPUTED_TABLES_HPP
#define SOBOL_PRECOMPUTED_TABLES_HPP

#include <array>
#include <cstddef>
#include <cstdint>

namespace sobol {
namespace precomputed {

// Maximum number of precomputed dimensions
constexpr std::size_t kMaxDimensions = )" << kMaxPrecomputedDimensions << R"(u;

// Number of direction number bits per dimension
constexpr std::size_t kDirectionBits = 32u;

)";
}

void write_primitive_polynomials(std::ostream& out) {
  std::cout << "Generating primitive polynomials for " << kMaxPrecomputedDimensions
            << " dimensions..." << std::endl;

  const auto polys = sobol::detail::generate_primitive_polynomials(kMaxPrecomputedDimensions);

  out << "// Primitive polynomials for each dimension (1-indexed)\n";
  out << "// These are used to generate direction numbers via recurrence relations\n";
  out << "constexpr std::array<std::uint32_t, kMaxDimensions> primitive_polynomials = {{\n";

  for (std::size_t i = 0; i < polys.size(); ++i) {
    if (i > 0 && i % 8 == 0) {
      out << "\n";
    }
    out << "  " << format_hex(polys[i]);
    if (i + 1 < polys.size()) {
      out << ",";
    }
    if (i % 8 < 7 && i + 1 < polys.size()) {
      out << " ";
    }
  }

  out << "\n}};\n\n";

  std::cout << "Generated " << polys.size() << " primitive polynomials." << std::endl;
}

void write_direction_numbers(std::ostream& out) {
  std::cout << "Generating direction numbers for " << kMaxPrecomputedDimensions
            << " dimensions..." << std::endl;

  const auto table = sobol::detail::build_direction_table(kMaxPrecomputedDimensions);

  out << "// Direction numbers for each dimension (dimensions x kDirectionBits)\n";
  out << "// Generated using Joe-Kuo method with Property A enforcement\n";
  out << "// Each dimension has 32 direction numbers used for Gray-code updates\n";
  out << "constexpr std::array<std::array<std::uint32_t, kDirectionBits>, kMaxDimensions> direction_numbers = {{\n";

  for (std::size_t dim = 0; dim < table.size(); ++dim) {
    out << "  // Dimension " << (dim + 1) << "\n";
    out << "  {{";

    for (std::size_t bit = 0; bit < sobol::detail::kSobolBits; ++bit) {
      if (bit > 0 && bit % 4 == 0) {
        out << "\n    ";
      }
      out << format_hex(table[dim][bit]);
      if (bit + 1 < sobol::detail::kSobolBits) {
        out << ", ";
      }
    }

    out << "}}";
    if (dim + 1 < table.size()) {
      out << ",";
    }
    out << "\n";
  }

  out << "}};\n\n";

  std::cout << "Generated direction numbers for " << table.size() << " dimensions." << std::endl;
}

void write_header_postamble(std::ostream& out) {
  out << R"(}  // namespace precomputed
}  // namespace sobol

#endif  // SOBOL_PRECOMPUTED_TABLES_HPP
)";
}

void write_documentation(std::ostream& out) {
  out << R"(
/*
TABLE GENERATION PROCESS
========================

This header file contains precomputed tables for Sobol sequence generation:

1. PRIMITIVE POLYNOMIALS
   - One polynomial per dimension (up to )" << kMaxPrecomputedDimensions << R"( dimensions)
   - Generated using is_primitive() check over GF(2)
   - Ensures polynomial has maximal order in the multiplicative group
   - Stored as 32-bit integers representing polynomial coefficients in binary

2. DIRECTION NUMBERS
   - 32 direction numbers per dimension (for 32-bit precision)
   - Generated using the Joe-Kuo method with Property A enforcement
   - Property A: Initial direction numbers maintain full rank for proper equidistribution
   - Recurrence relation applied to generate remaining direction numbers

PROPERTY A ENFORCEMENT
=======================

For each dimension d > 1:
  - Primitive polynomial of degree s is selected
  - Initial direction numbers m[1]...m[s] are chosen to ensure full rank
  - Full rank is verified using Gaussian elimination over GF(2)
  - This guarantees good two-dimensional projections (Joe & Kuo, 2008)

USAGE
=====

Include this header to access precomputed tables:

  #include "sobol/precomputed_tables.hpp"

  // Access primitive polynomial for dimension i (0-indexed)
  auto poly = sobol::precomputed::primitive_polynomials[i];

  // Access direction numbers for dimension i, bit j
  auto dir_num = sobol::precomputed::direction_numbers[i][j];

REGENERATION
============

To regenerate this file:

  1. Build the generator: cmake --build build --target generate_tables
  2. Run: ./build/tools/generate_tables
  3. The file include/sobol/precomputed_tables.hpp will be updated

REFERENCES
==========

Joe, S. and Kuo, F. Y. (2008). "Constructing Sobol sequences with better
two-dimensional projections". SIAM Journal on Scientific Computing,
30(5):2635-2654.
*/
)";
}

}  // namespace

int main(int argc, char* argv[]) {
  const std::string output_file = argc > 1
    ? argv[1]
    : "include/sobol/precomputed_tables.hpp";

  std::cout << "Generating precomputed Sobol tables..." << std::endl;
  std::cout << "Output file: " << output_file << std::endl;

  std::ofstream out(output_file);
  if (!out) {
    std::cerr << "Error: Could not open output file: " << output_file << std::endl;
    return 1;
  }

  write_header_preamble(out);
  write_primitive_polynomials(out);
  write_direction_numbers(out);
  write_header_postamble(out);
  write_documentation(out);

  out.close();

  std::cout << "Successfully generated " << output_file << std::endl;
  std::cout << "Tables support up to " << kMaxPrecomputedDimensions << " dimensions." << std::endl;

  return 0;
}
