// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sobol_points
Rcpp::NumericMatrix sobol_points(int n, int dim, double skip);
RcppExport SEXP _sobol_sobol_points(SEXP nSEXP, SEXP dimSEXP, SEXP skipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< double >::type skip(skipSEXP);
    rcpp_result_gen = Rcpp::wrap(sobol_points(n, dim, skip));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_sobol_generator_module();

static const R_CallMethodDef CallEntries[] = {
    {"_sobol_sobol_points", (DL_FUNC) &_sobol_sobol_points, 3},
    {"_rcpp_module_boot_sobol_generator_module", (DL_FUNC) &_rcpp_module_boot_sobol_generator_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_sobol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
